// ─────────────────────────────────────────────
// Static Data for UK Physics PhD Finder Agent
// For Nepali MSc Physics Students from Tribhuvan University
// ─────────────────────────────────────────────

export interface Institution {
  id: string
  name: string
  city: string
  country: string  // UK region/country (England, Scotland, Wales, Northern Ireland)
  type: 'University' | 'Research Institute' | 'National Facility'
  department: string
  researchGroup: string | null
  url: string
  fields: string
  phdType: string
  deadline: string
  admission: 'Rolling' | 'Semester-based'
  deadlines: {
    october_entry: string
    january_entry: string
    rolling: boolean
  }
  internationalTuitionGbp: number
  funding: {
    doctoralScholarshipAvailable: boolean
    doctoralStipendGbp: number
    epsrcFunded: boolean
    cscEligible: boolean
    russellGroup: boolean
    ukriFunded: boolean
  }
  ieltsMinimum: number
  contractType: string
  monthlyGbp: number | null
  languageInstruction: string
  englishLabLife: boolean
  notableProfessors: string
  requiredDocuments: string
  notesForNepali: string
  watchlisted: boolean
  lastUpdated: string
  go8: boolean // Russell Group flag for API compat
}

export interface ScholarshipInfo {
  id: string
  title: string
  category: string
  content: string
}

// ─────────────────────────────────────────────
// UK UNIVERSITIES & RESEARCH INSTITUTES
// ─────────────────────────────────────────────
export const institutions: Institution[] = [
  // ========================
  // RUSSELL GROUP UNIVERSITIES
  // ========================
  {
    id: 'oxford',
    name: 'University of Oxford',
    city: 'Oxford',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'Clarendon Laboratory',
    url: 'https://www.physics.ox.ac.uk/',
    fields: 'Quantum Computing|Particle Physics|Astrophysics|Condensed Matter',
    phdType: 'DPhil in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'November deadline', rolling: false },
    internationalTuitionGbp: 29700,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 7.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Sir Roger Penrose, Henry Snaith, Andrew Briggs',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Oxford-CSC scholarship available for Nepali students. Very competitive but excellent funding.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    city: 'Cambridge',
    country: 'England',
    type: 'University',
    department: 'Department of Physics (Cavendish Laboratory)',
    researchGroup: 'Cavendish Laboratory',
    url: 'https://www.phy.cam.ac.uk/',
    fields: 'Theoretical Physics|Quantum Matter|Particle Physics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'November deadline', rolling: false },
    internationalTuitionGbp: 33900,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 7.0,
    contractType: 'EPSRC/UKRI Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'David Tong, Suchitra Sebastian, Mete Atatüre',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Cambridge Trust scholarships available. Gates Cambridge also open to Nepali students.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    city: 'London',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: 'Blackett Laboratory',
    url: 'https://www.imperial.ac.uk/physics',
    fields: 'Quantum Physics|Particle Physics|Materials Science',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 31800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Terry Rudolph, Michele Dougherty, Claudia de Rham',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'President\'s PhD Scholarships available. Imperial-CSC programme for Chinese students but other routes available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'ucl',
    name: 'University College London (UCL)',
    city: 'London',
    country: 'England',
    type: 'University',
    department: 'Department of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.ucl.ac.uk/physics-astronomy',
    fields: 'Condensed Matter|Quantum Computing|Biophysics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 29400,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Andrew Fisher, Jonathan Oppenheim, Sougato Bose',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'UCL has strong Commonwealth scholarship links. Good for Nepali students.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'edinburgh',
    name: 'University of Edinburgh',
    city: 'Edinburgh',
    country: 'Scotland',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: 'Higgs Centre for Theoretical Physics',
    url: 'https://www.ph.ed.ac.uk/',
    fields: 'Astrophysics|Particle Physics|Quantum Computing',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'November deadline', rolling: false },
    internationalTuitionGbp: 28950,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Peter Higgs (Emeritus), Richard Kenway, Elsen Vlieg',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Higgs Centre offers excellent theoretical physics training. Scotland has lower living costs than London.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'manchester',
    name: 'University of Manchester',
    city: 'Manchester',
    country: 'England',
    type: 'University',
    department: 'Department of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.manchester.ac.uk/physics',
    fields: 'Particle Physics|Nuclear Physics|Materials Science',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 28000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Andre Geim, Kostya Novoselov, Brian Cox',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Home of graphene! Nobel Prize-winning department. Lower cost of living than London.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'durham',
    name: 'Durham University',
    city: 'Durham',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.durham.ac.uk/departments/academic/physics/',
    fields: 'Astronomy|Particle Physics|Condensed Matter',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26500,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Carlos Frenk, Richard Bower, John Lucey',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Excellent for astronomy/astrophysics. Institute for Computational Cosmology is world-class.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'bristol',
    name: 'University of Bristol',
    city: 'Bristol',
    country: 'England',
    type: 'University',
    department: 'School of Physics',
    researchGroup: null,
    url: 'https://www.bristol.ac.uk/physics/',
    fields: 'Quantum Engineering|Particle Physics|Nanophysics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 27200,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Sir Michael Berry, Ruth Oulton, Noah Linden',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Quantum Engineering Technology Labs is world-leading. Bristol is a vibrant student city.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'warwick',
    name: 'University of Warwick',
    city: 'Coventry',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://warwick.ac.uk/fac/sci/physics/',
    fields: 'Particle Physics|Astrophysics|Theoretical Physics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 27460,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Bill Spence, Mark Smith, Gareth Alexander',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Strong in particle physics (CERN collaboration) and theoretical physics. Chancellor\'s International Scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'birmingham',
    name: 'University of Birmingham',
    city: 'Birmingham',
    country: 'England',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.birmingham.ac.uk/schools/physics/index.aspx',
    fields: 'Nuclear Physics|Particle Physics|Quantum Materials',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26640,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Willem van der Geer, Cristina Lazzeroni, Martin Freer',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Excellent for nuclear physics. Second largest city in UK with diverse community.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'glasgow',
    name: 'University of Glasgow',
    city: 'Glasgow',
    country: 'Scotland',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.gla.ac.uk/schools/physics/',
    fields: 'Particle Physics|Gravitational Physics|Optics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 25290,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Sheila Rowan, Graham Turnbull, Ralf Kaiser',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'LIGO gravitational wave detection group. Scotland has lower living costs. College of Science & Engineering scholarships.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'leeds',
    name: 'University of Leeds',
    city: 'Leeds',
    country: 'England',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://eps.leeds.ac.uk/physics',
    fields: 'Condensed Matter|Polymer Physics|Medical Physics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26500,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Helen Gleeson, Jiannis Pachos, Oscar Cespedes',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Strong in condensed matter and polymer physics. International Scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'sheffield',
    name: 'University of Sheffield',
    city: 'Sheffield',
    country: 'England',
    type: 'University',
    department: 'Department of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.sheffield.ac.uk/physics',
    fields: 'Particle Physics|Astrophysics|Materials Science',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 27050,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Neil Bartlett, David Coster, Elizabeth Winstanley',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Good particle physics group. Sheffield is affordable city for students.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'nottingham',
    name: 'University of Nottingham',
    city: 'Nottingham',
    country: 'England',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.nottingham.ac.uk/physics/',
    fields: 'Quantum Optics|Condensed Matter|Nanoscience',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26700,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Sir Peter Knight, Philip Moriarty, Yuri Pusey',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Strong quantum optics group. Developing Solutions Scholarships for students from developing countries.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'southampton',
    name: 'University of Southampton',
    city: 'Southampton',
    country: 'England',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.southampton.ac.uk/physics',
    fields: 'Photonics|Quantum Computing|Astronomy',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26850,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: "Peter Hobson, Tim Birks, Jeremy O'Brien",
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Excellent for photonics and optoelectronics. Zepler Institute is world-class.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'kcl',
    name: "King's College London",
    city: 'London',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.kcl.ac.uk/nms/depts/physics/index.aspx',
    fields: 'Theoretical Physics|Condensed Matter|Biophysics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 27900,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 19237,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1603,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'John Ellis, Tania Monteiro, Anatoly Zayats',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'John Ellis (CERN theorist) is based here. King\'s International Scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'liverpool',
    name: 'University of Liverpool',
    city: 'Liverpool',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.liverpool.ac.uk/physics/',
    fields: 'Particle Physics|Nuclear Physics|Materials Science',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 25950,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Tara Shears, Jonathon Coleman, Sven Van Loo',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Strong CERN group. Liverpool is an affordable city for students.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'york',
    name: 'University of York',
    city: 'York',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.york.ac.uk/physics/',
    fields: 'Quantum Technology|Plasma Physics|Nuclear Physics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26500,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Stefano Morigi, Rodolfo Hermans, Kieran Flanagan',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Excellent for quantum technology and plasma physics. York is a beautiful and affordable city.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'cardiff',
    name: 'Cardiff University',
    city: 'Cardiff',
    country: 'Wales',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.cardiff.ac.uk/physics-astronomy',
    fields: 'Gravitational Physics|Astronomy|Condensed Matter',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 25450,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Patrick Sutton, Bernard Schutz, Walter Gelletly',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'LIGO gravitational wave group. Wales has lower living costs. Vice-Chancellor\'s International Scholarships.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },
  {
    id: 'newcastle',
    name: 'Newcastle University',
    city: 'Newcastle',
    country: 'England',
    type: 'University',
    department: 'School of Mathematics, Statistics & Physics',
    researchGroup: null,
    url: 'https://www.ncl.ac.uk/maths-physics/',
    fields: 'Quantum Computing|Materials Science|Astrophysics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 26000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: true,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Anvar Shukurov, Andrew Willmott, Zabe Hussain',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Newcastle is affordable and welcoming. International Family Scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: true,
  },

  // ========================
  // OTHER NOTABLE UNIVERSITIES
  // ========================
  {
    id: 'st-andrews',
    name: 'University of St Andrews',
    city: 'St Andrews',
    country: 'Scotland',
    type: 'University',
    department: 'School of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.st-andrews.ac.uk/physics/',
    fields: 'Photonics|Quantum Optics|Condensed Matter',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 24500,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/University Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Kishan Dholakia, David Grier, Miles Padgett',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'World-leading photonics group. St Andrews is Scotland\'s oldest university. STFC-funded positions available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'sussex',
    name: 'University of Sussex',
    city: 'Brighton',
    country: 'England',
    type: 'University',
    department: 'Department of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.sussex.ac.uk/physics/',
    fields: 'Quantum Technology|Particle Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 22000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 16000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.0,
    contractType: 'EPSRC/University Studentship',
    monthlyGbp: 1333,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Winfried Hensinger, Alessandro Romito, David Seery',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Quantum technology pioneer (Winfried Hensinger built first practical quantum computer blueprint). Chancellor\'s International Scholarships.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'lancaster',
    name: 'Lancaster University',
    city: 'Lancaster',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.lancaster.ac.uk/physics/',
    fields: 'Low-Temperature Physics|Quantum Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 21800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 16000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1333,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'George Pickett, Dmitry Zmeev, Viktor Tsepelin',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'World-leading low-temperature physics. Home to the ultra-low temperature record. International Scholarships available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'qmul',
    name: 'Queen Mary University of London',
    city: 'London',
    country: 'England',
    type: 'University',
    department: 'School of Physical & Chemical Sciences',
    researchGroup: null,
    url: 'https://www.qmul.ac.uk/spcs/',
    fields: 'Particle Physics|String Theory',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 24000,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC/STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'David Berman, Sanjaye Ramgoolam, Gabriele Travaglini',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Strong string theory group. Part of University of London. Principal\'s PhD Studentships available.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'royal-holloway',
    name: 'Royal Holloway, University of London',
    city: 'Egham',
    country: 'England',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.royalholloway.ac.uk/physics/',
    fields: 'Particle Physics|Quantum Optics',
    phdType: 'PhD in Physics',
    deadline: 'January 2026',
    admission: 'Semester-based',
    deadlines: { october_entry: 'January deadline', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 22800,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 18622,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'STFC Studentship',
    monthlyGbp: 1552,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Pedro Teixeira-Dias, Gavin Davies, Andrew Casey',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Excellent for particle physics (T2K and LHC experiments). Beautiful campus near London.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'exeter',
    name: 'University of Exeter',
    city: 'Exeter',
    country: 'England',
    type: 'University',
    department: 'Department of Physics & Astronomy',
    researchGroup: null,
    url: 'https://www.exeter.ac.uk/physics/',
    fields: 'Quantum Systems|Metamaterials',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 23500,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 16000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1333,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Bill Barnes, Peter de Groot, Mikhail Portnoi',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Strong in metamaterials and quantum systems. Global Excellence Scholarships for international students.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'strathclyde',
    name: 'University of Strathclyde',
    city: 'Glasgow',
    country: 'Scotland',
    type: 'University',
    department: 'Department of Physics',
    researchGroup: null,
    url: 'https://www.strath.ac.uk/science/physics/',
    fields: 'Photonics|Plasma Physics',
    phdType: 'PhD in Physics',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 22050,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 16000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'EPSRC Studentship',
    monthlyGbp: 1333,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Alison Yao, Paul Griffin, David Robertson',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Excellent for photonics and plasma physics. Strathclyde is in Glasgow — affordable Scottish city.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },

  // ========================
  // NATIONAL FACILITIES
  // ========================
  {
    id: 'ral',
    name: 'Rutherford Appleton Laboratory (RAL)',
    city: 'Didcot',
    country: 'England',
    type: 'National Facility',
    department: 'STFC Rutherford Appleton Laboratory',
    researchGroup: 'ISIS Neutron and Muon Source',
    url: 'https://www.ukri.org/councils/stfc/',
    fields: 'Particle Physics|Neutron Science|Laser Science',
    phdType: 'PhD (partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 20000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'STFC Studentship',
    monthlyGbp: 1667,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Various STFC scientists, CERN collaborators',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'UK\'s premier national lab. Students register at Oxford, Reading, or other partner universities. STFC funds tuition + stipend.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'daresbury',
    name: 'Daresbury Laboratory',
    city: 'Warrington',
    country: 'England',
    type: 'National Facility',
    department: 'STFC Daresbury Laboratory',
    researchGroup: 'Hartree Centre',
    url: 'https://www.ukri.org/councils/stfc/',
    fields: 'Accelerator Science|Computational Science',
    phdType: 'PhD (partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 20000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'STFC Studentship',
    monthlyGbp: 1667,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Various STFC scientists, accelerator physics group',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Home to the Hartree Centre and CLARA accelerator. Students register at Liverpool, Manchester, or other partner universities.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'npl',
    name: 'National Physical Laboratory (NPL)',
    city: 'Teddington',
    country: 'England',
    type: 'National Facility',
    department: 'National Physical Laboratory',
    researchGroup: 'Quantum Metrology Institute',
    url: 'https://www.npl.co.uk/',
    fields: 'Quantum Metrology|Measurement Science',
    phdType: 'PhD (partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 20000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'NPL/UKRI Studentship',
    monthlyGbp: 1667,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Various NPL scientists, Quantum Metrology Institute',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'UK\'s national measurement institute. Quantum Metrology Institute is world-leading. Students register at partner universities.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
  {
    id: 'uk-atc',
    name: 'UK Astronomy Technology Centre',
    city: 'Edinburgh',
    country: 'Scotland',
    type: 'National Facility',
    department: 'UK ATC',
    researchGroup: null,
    url: 'https://www.ukri.org/councils/stfc/',
    fields: 'Astronomy|Instrumentation',
    phdType: 'PhD (partner university)',
    deadline: 'Rolling',
    admission: 'Rolling',
    deadlines: { october_entry: 'Rolling', january_entry: 'Rolling', rolling: true },
    internationalTuitionGbp: 0,
    funding: {
      doctoralScholarshipAvailable: true,
      doctoralStipendGbp: 20000,
      epsrcFunded: true,
      cscEligible: true,
      russellGroup: false,
      ukriFunded: true,
    },
    ieltsMinimum: 6.5,
    contractType: 'STFC Studentship',
    monthlyGbp: 1667,
    languageInstruction: 'English',
    englishLabLife: true,
    notableProfessors: 'Various STFC astronomers and instrumentation scientists',
    requiredDocuments: 'Research proposal, transcripts, references, IELTS, CV',
    notesForNepali: 'Designs and builds instruments for world-leading telescopes. Students register at Edinburgh or other Scottish universities.',
    watchlisted: false,
    lastUpdated: '2025-01-15',
    go8: false,
  },
]

// ─────────────────────────────────────────────
// UK SCHOLARSHIPS
// ─────────────────────────────────────────────
export const scholarships: ScholarshipInfo[] = [
  {
    id: 'epsrc-studentship',
    title: 'EPSRC Studentship',
    category: 'Government',
    content: 'The Engineering and Physical Sciences Research Council (EPSRC) funds PhD studentships across the UK. Covers full tuition fees (home rate) + £18,622/year stipend + training support grant. International students may need to cover the fee difference. Apply through university departments — not a central portal. Most Russell Group universities offer EPSRC-funded PhD positions.',
  },
  {
    id: 'commonwealth-scholarship',
    title: 'Commonwealth Scholarship (CSC)',
    category: 'International',
    content: 'The Commonwealth Scholarship Commission provides full funding for students from Commonwealth countries including Nepal. Covers full tuition fees, living allowance, return airfare from Nepal, and study travel grants. Apply through the British Embassy in Kathmandu or Ministry of Education Nepal. Extremely competitive but fully funded.',
  },
  {
    id: 'ukri-studentship',
    title: 'UKRI Studentship',
    category: 'Government',
    content: 'UK Research and Innovation (UKRI) provides doctoral studentships through all seven research councils (EPSRC, STFC, MRC, BBSRC, NERC, AHRC, ESRC). Covers tuition fees + £18,622/year stipend. STFC funds astronomy and particle physics PhDs specifically. Apply through university departments.',
  },
  {
    id: 'chevening-scholarship',
    title: 'Chevening Scholarship',
    category: 'Government',
    content: 'UK government\'s international awards programme. Full tuition fees + living allowance + travel costs. Primarily for one-year master\'s degrees but some PhD options available. Apply through Chevening website. Nepali students are eligible. Requires 2 years work experience and leadership potential.',
  },
  {
    id: 'university-scholarships',
    title: 'University-specific Scholarships',
    category: 'University',
    content: 'Most UK universities offer their own doctoral scholarships. Examples: Oxford Clarendon Fund, Cambridge Gates Trust, Imperial President\'s Scholarship, UCL Graduate Research Scholarship. These often cover full tuition (international rate) + stipend. Check individual university websites for deadlines and eligibility.',
  },
  {
    id: 'stfc-studentship',
    title: 'STFC Studentship',
    category: 'Government',
    content: 'Science and Technology Facilities Council funds PhD students in astronomy, particle physics, nuclear physics, and accelerator science. Covers tuition fees + £18,622/year stipend. Students may be based at universities or at STFC national labs (RAL, Daresbury, UK ATC). Apply through university physics departments.',
  },
  {
    id: 'royal-society-studentship',
    title: 'Royal Society Studentship',
    category: 'Government',
    content: 'The Royal Society offers research fellowships and studentships for exceptional researchers. Newton International Fellowship for early-career researchers from developing countries. Also provides Dorothy Hodgkin Fellowships. Highly prestigious and competitive.',
  },
  {
    id: 'gcrf-scholarships',
    title: 'GCRF Scholarships',
    category: 'International',
    content: 'Global Challenges Research Fund supports research addressing challenges in developing countries. Some PhD positions are available through GCRF-funded projects at UK universities. Often focused on applied physics, renewable energy, or climate-related research. Check individual university projects.',
  },
  {
    id: 'great-scholarship',
    title: 'GREAT Scholarship',
    category: 'International',
    content: 'GREAT Scholarships offer £10,000 towards tuition fees for students from selected countries. Jointly funded by UK government and participating universities. Available for specific master\'s and PhD programmes. Check the British Council Nepal website for eligible countries and programmes.',
  },
  {
    id: 'charles-wallace-trust',
    title: 'Charles Wallace Trust Scholarship',
    category: 'International',
    content: 'Charles Wallace Pakistan Trust provides funding for students from South Asia including Nepal. Offers grants towards living costs and tuition. Awards are typically £500-£2,500 but can supplement other funding. Apply through British Council Nepal.',
  },
  {
    id: 'british-council-scholarship',
    title: 'British Council Scholarship',
    category: 'International',
    content: 'British Council Nepal offers various scholarship programmes and can provide guidance on UK study options. They administer some GREAT Scholarships and have information on other funding opportunities. Visit British Council office in Kathmandu for advice and application support.',
  },
]

// ─────────────────────────────────────────────
// SEARCH FUNCTION
// ─────────────────────────────────────────────
export function searchScholarships(query: string): ScholarshipInfo[] {
  const q = query.toLowerCase()
  return scholarships.filter(
    (s) =>
      s.title.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      s.content.toLowerCase().includes(q)
  )
}
